.PHONY: clean All

All:
	@echo "----------Building project:[ EchoBot - Debug ]----------"
	@cd "EchoBot" && $(MAKE) -f  "EchoBot.mk"
clean:
	@echo "----------Cleaning project:[ EchoBot - Debug ]----------"
	@cd "EchoBot" && $(MAKE) -f  "EchoBot.mk" clean
