package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Capture plugin data buffer type enumeration.
 * */
public abstract class CaptureBufferType {

	@IntDef(flag=true, value={Unknown, PixelBuffer, Texture3D, PixelBuffer3D})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

	public static final int Unknown             	=	Types.CAPTURE_BUFFERTYPE_UNKNOWN;
			/** The data is stored as pixel data usually in rgba order. */
	public static final int PixelBuffer         	=	Types.CAPTURE_BUFFERTYPE_PIXELBUFFER;
			/** The data follows either D3D or OpenGL texture format. */
	public static final int Texture3D           	=	Types.CAPTURE_BUFFERTYPE_TEXTURE_3D;
			/** The data follows either D3D or OpenGL buffer format. */
	public static final int PixelBuffer3D       	=	Types.CAPTURE_BUFFERTYPE_PIXELBUFFER_3D;
		
}





