package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/** 
 * Capture subtype enumeration.
 * */
public abstract class CaptureType {

	@IntDef(flag=true, value={Unknown, Screen, AppWindow, Camera})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

	public static final int Unknown             	=	Types.CAPTURE_TYPE_UNKNOWN;
			/** A screen such as the dekstop window, 
			 *  where the device may cover only part of the display.
			 *  where the device may cover only part of the display.
			 *  The screen size must not be changed as long as the grabber class is used by at least one instance. */
	public static final int Screen              	=	Types.CAPTURE_TYPE_SCREEN;
			/** An application window, where each device may have a different app window and may cover only part of the window. */
	public static final int AppWindow           	=	Types.CAPTURE_TYPE_APP_WINDOW;
			/** Camera */
	public static final int Camera              	=	Types.CAPTURE_TYPE_CAMERA;
}





