package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Mediator device class types enumeration.
 * */
public abstract class DeviceClass {

	@IntDef(flag=true, value={All, Nearby, Mediator})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

	public static final int All                 	=	Types.MEDIATOR_DEVICE_CLASS_ALL;
	public static final int Nearby              	=	Types.MEDIATOR_DEVICE_CLASS_NEARBY;
	public static final int Mediator            	=	Types.MEDIATOR_DEVICE_CLASS_MEDIATOR;
		
}





