package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/** 
 * Device Connect Status enumeration. Represents the same values as for DEVICE_STATUS_* 
 * */
public abstract class DeviceStatus {

	@IntDef(flag=true, value={Deleteable, Created, ConnectInProgress, Connected})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

			/** Deleteable. Device object has been disabled.&nbsp; 
			 * "Garbage Collection" should dispose and delete the object on the next occasion. 
			 * "Garbage Collection" should dispose and delete the object on the next occasion. 
			 * */
	public static final int Deleteable          	=	Types.DEVICE_STATUS_DELETEABLE;
			/** Device object has just been created. */
	public static final int Created             	=	Types.DEVICE_STATUS_CREATED;
			/** Connect in progress. Device object has been created and the connecting task is in progress. */
	public static final int ConnectInProgress   	=	Types.DEVICE_STATUS_CONNECT_IN_PROGRESS;
			/** Connected. Device object is connected to the destination device and active. */
	public static final int Connected           	=	Types.DEVICE_STATUS_CONNECTED;
}





