package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * DeviceInfoAttr attribute enumeration.
 * */
public abstract class DeviceInfoFlag {

	@IntDef(flag=true, value={Disposed, DisposedChanged, IsConnected, ConnectProgress, UserName, Identity, Platform, 
			DeviceType, NativeID, IP, IPe, TcpPort, UdpPort, Unavailable, 
			BroadcastFound, DirectContact, AppContext, PortalCreated, ObjectID, Flags})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

	public static final int Disposed            	=	Types.ENVIRONS_OBJECT_DISPOSED;
	public static final int DisposedChanged     	=	Types.DEVICE_INFO_ATTR_DISPOSED;
	public static final int IsConnected         	=	Types.DEVICE_INFO_ATTR_ISCONNECTED;
	public static final int ConnectProgress     	=	Types.DEVICE_INFO_ATTR_CONNECT_PROGRESS;
	public static final int UserName            	=	Types.DEVICE_INFO_ATTR_USER_NAME;
	public static final int Identity            	=	Types.DEVICE_INFO_ATTR_IDENTITY;
	public static final int Platform            	=	Types.DEVICE_INFO_ATTR_DEVICE_PLATFORM;
	public static final int DeviceType          	=	Types.DEVICE_INFO_ATTR_DEVICE_TYPE;
	public static final int NativeID            	=	Types.DEVICE_INFO_ATTR_NATIVEID;
	public static final int IP                  	=	Types.DEVICE_INFO_ATTR_IP;
	public static final int IPe                 	=	Types.DEVICE_INFO_ATTR_IPE;
	public static final int TcpPort             	=	Types.DEVICE_INFO_ATTR_TCP_PORT;
	public static final int UdpPort             	=	Types.DEVICE_INFO_ATTR_UDP_PORT;
	public static final int Unavailable         	=	Types.DEVICE_INFO_ATTR_UNAVAILABLE;
	public static final int BroadcastFound      	=	Types.DEVICE_INFO_ATTR_BROADCAST_FOUND;
	public static final int DirectContact       	=	Types.DEVICE_INFO_ATTR_DIRECT_CONTACT;
	public static final int AppContext          	=	Types.DEVICE_INFO_ATTR_APP_CONTEXT;
	public static final int PortalCreated       	=	Types.DEVICE_INFO_ATTR_PORTAL_CREATED;
	public static final int ObjectID            	=	Types.DEVICE_INFO_ATTR_OBJID;
	public static final int Flags               	=	Types.DEVICE_INFO_ATTR_FLAGS;
		
}





