package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/** 
 * Encoder buffer data type enumeration.
 * */
public abstract class EncoderBufferType {

	@IntDef(flag=true, value={Unknown, ARGB, YUV420})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

	public static final int Unknown             	=	Types.ENCODER_BUFFERTYPE_UNKNOWN;
			/** Windows ARGB. */
	public static final int ARGB                	=	Types.ENCODER_BUFFERTYPE_ARGB;
			/** I420. */
	public static final int YUV420              	=	Types.ENCODER_BUFFERTYPE_YUV420;
}





