package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * FileInfo attribute enumeration.
 * */
public abstract class FileInfoFlag {

	@IntDef(flag=true, value={Disposed, Created, Available, SendProgress, ReceiveProgress})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

	public static final int Disposed            	=	Types.ENVIRONS_OBJECT_DISPOSED;
	public static final int Created             	=	Types.FILE_INFO_ATTR_CREATED;
	public static final int Available           	=	Types.FILE_INFO_ATTR_AVAILABLE;
	public static final int SendProgress        	=	Types.FILE_INFO_ATTR_SEND_PROGRESS;
	public static final int ReceiveProgress     	=	Types.FILE_INFO_ATTR_RECEIVE_PROGRESS;
		
}





