package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Input type enumeration.
 * */
public abstract class InputType {

	@IntDef(flag=true, value={Cursor, Finger, Pen, Marker, Blob})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

	public static final int Cursor              	=	Types.INPUT_TYPE_CURSOR;
	public static final int Finger              	=	Types.INPUT_TYPE_FINGER;
	public static final int Pen                 	=	Types.INPUT_TYPE_PEN;
	public static final int Marker              	=	Types.INPUT_TYPE_MARKER;
	public static final int Blob                	=	Types.INPUT_TYPE_BLOB;
		
}





