package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Input source commands enumeration.
 * */
public abstract class InputCommand {

	@IntDef(flag=true, value={Init, Add, Change, Drop, Cancel, Flush, FollowUp, 
	})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

	public static final int Init                	=	Types.INPUTSOURCE_COMMAND_INIT;
	public static final int Add                 	=	Types.INPUTSOURCE_COMMAND_ADD;
	public static final int Change              	=	Types.INPUTSOURCE_COMMAND_CHANGE;
	public static final int Drop                	=	Types.INPUTSOURCE_COMMAND_DROP;
	public static final int Cancel              	=	Types.INPUTSOURCE_COMMAND_CANCEL;
	public static final int Flush               	=	Types.INPUTSOURCE_COMMAND_FLUSH;
	public static final int FollowUp            	=	Types.INPUTSOURCE_COMMAND_FOLLOWUP;
		
}





