package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/** 
 * Extension plugin interface type enumeration.
 * */
public abstract class InterfaceType {

	@IntDef(flag=true, value={Unknown, Capture, Render, Encoder, Decoder, Tracker, Sensor, 
			InputRecognizer, OrientationRecognizer, ExtThread})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

	public static final int Unknown             	=	Types.INTERFACE_TYPE_UNKNOWN;
			/** A Capture plugin grabs images from a capture source and provides the image buffer to the pipeline. */
	public static final int Capture             	=	Types.INTERFACE_TYPE_CAPTURE;
			/** A Render plugin renders a capture image (compare, rotate, scale, etc.). */
	public static final int Render              	=	Types.INTERFACE_TYPE_RENDER;
			/** An Encoder encodes the rendered image to a target format / stream. */
	public static final int Encoder             	=	Types.INTERFACE_TYPE_ENCODER;
			/** A Decoder decodes stream packets to images */
	public static final int Decoder             	=	Types.INTERFACE_TYPE_DECODER;
			/** A Tracker that analyzes raw images for objects, touches, etc. */
	public static final int Tracker             	=	Types.INTERFACE_TYPE_TRACKER;
			/** A Sensor that implements a sensor of type SensorType_t */
	public static final int Sensor              	=	Types.INTERFACE_TYPE_SENSOR;
			/** A InputRecognizer is called back and provided a list of the current TouchDispatch state in order to perform gesture recognition. */
	public static final int InputRecognizer     	=	Types.INTERFACE_TYPE_INPUT_RECOGNIZER;
			/** A TouchRecognizer is called back and provided a list of the current TouchDispatch state in order to perform gesture recognition. */
	public static final int OrientationRecognizer          	=	Types.INTERFACE_TYPE_ORIENTATION_RECOGNIZER;
			/** An external implementation of a thread function. */
	public static final int ExtThread           	=	Types.INTERFACE_TYPE_EXTENSION_THREAD;
		
}





