package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Environs detectable platforms.
 * */
public abstract class Platforms {

	@IntDef(flag=true, value={Unknown, MSSurface_Flag, MSSUR01, SAMSUR40, iPad_Flag, iPad1, iPad2, 
			iPad2Mini, iPad3, iPad4, iPad4Air, iPad4Mini, iPad4Mini3, iPad5Air2, 
			iPhone_Flag, iPhone4, iPhone5, iPhone6, iPhone6p, MultiTaction_Flag, MultiTaction55, 
			OSX_Flag, MacBook_Flag, MacMini_Flag, Linux_Flag, Raspberry_Flag, Windows_Flag, WindowsVista, 
			WindowsXP, Windows7, Windows8, Windows10, Tablet_Flag, Smartphone_Flag, Tabletop_Flag, 
			Display_Flag, LocationNode_Flag})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

	public static final int Unknown             	=	Types.ENVIRONS_PLATFORMS_UNKNOWN;
			/** MS Surface Tabletops */
	public static final int MSSurface_Flag      	=	Types.ENVIRONS_PLATFORMS_MSSURFACE_FLAG;
			/** Surface 1 tabletop */
	public static final int MSSUR01             	=	Types.ENVIRONS_PLATFORMS_MSSUR01;
			/** Samsung SUR40 PixelSense */
	public static final int SAMSUR40            	=	Types.ENVIRONS_PLATFORMS_SAMSUR40;
		
			/** iPad */
	public static final int iPad_Flag           	=	Types.ENVIRONS_PLATFORMS_IPAD_FLAG;
	public static final int iPad1               	=	Types.ENVIRONS_PLATFORMS_IPAD1;
	public static final int iPad2               	=	Types.ENVIRONS_PLATFORMS_IPAD2;
	public static final int iPad2Mini           	=	Types.ENVIRONS_PLATFORMS_IPAD2MINI;
	public static final int iPad3               	=	Types.ENVIRONS_PLATFORMS_IPAD3;
	public static final int iPad4               	=	Types.ENVIRONS_PLATFORMS_IPAD4;
	public static final int iPad4Air            	=	Types.ENVIRONS_PLATFORMS_IPAD4AIR;
	public static final int iPad4Mini           	=	Types.ENVIRONS_PLATFORMS_IPAD4MINI;
	public static final int iPad4Mini3          	=	Types.ENVIRONS_PLATFORMS_IPAD4MINI3;
	public static final int iPad5Air2           	=	Types.ENVIRONS_PLATFORMS_IPAD5AIR2;
		
			/** iPhones */
	public static final int iPhone_Flag         	=	Types.ENVIRONS_PLATFORMS_IPHONE_FLAG;
	public static final int iPhone4             	=	Types.ENVIRONS_PLATFORMS_IPHONE4;
	public static final int iPhone5             	=	Types.ENVIRONS_PLATFORMS_IPHONE5;
	public static final int iPhone6             	=	Types.ENVIRONS_PLATFORMS_IPHONE6;
	public static final int iPhone6p            	=	Types.ENVIRONS_PLATFORMS_IPHONE6P;
		
			/** MultiTaction Cells */
	public static final int MultiTaction_Flag   	=	Types.ENVIRONS_PLATFORMS_MULTITACTION_FLAG;
			/** MultiTaction Cell 55. */
	public static final int MultiTaction55      	=	Types.ENVIRONS_PLATFORMS_MULTITACTION55;
		
	public static final int OSX_Flag            	=	Types.ENVIRONS_PLATFORMS_OSX_FLAG;
	public static final int MacBook_Flag        	=	Types.ENVIRONS_PLATFORMS_MACBOOK_FLAG;
	public static final int MacMini_Flag        	=	Types.ENVIRONS_PLATFORMS_MACMINI_FLAG;
		
	public static final int Linux_Flag          	=	Types.ENVIRONS_PLATFORMS_LINUX_FLAG;
	public static final int Raspberry_Flag      	=	Types.ENVIRONS_PLATFORMS_RASPBERRY;
		
	public static final int Windows_Flag        	=	Types.ENVIRONS_PLATFORMS_WINDOWS_FLAG;
	public static final int WindowsVista        	=	Types.ENVIRONS_PLATFORMS_WINDOWSVISTA;
	public static final int WindowsXP           	=	Types.ENVIRONS_PLATFORMS_WINDOWSXP;
	public static final int Windows7            	=	Types.ENVIRONS_PLATFORMS_WINDOWS7;
	public static final int Windows8            	=	Types.ENVIRONS_PLATFORMS_WINDOWS8;
	public static final int Windows10           	=	Types.ENVIRONS_PLATFORMS_WINDOWS10;
		
	public static final int Tablet_Flag         	=	Types.ENVIRONS_PLATFORMS_TABLET_FLAG;
	public static final int Smartphone_Flag     	=	Types.ENVIRONS_PLATFORMS_SMARTPHONE_FLAG;
	public static final int Tabletop_Flag       	=	Types.ENVIRONS_PLATFORMS_TABLETOP_FLAG;
	public static final int Display_Flag        	=	Types.ENVIRONS_PLATFORMS_DISPLAY_FLAG;
		
	public static final int LocationNode_Flag   	=	Types.ENVIRONS_PLATFORMS_LOCATIONNODE_FLAG;
		
		
		
		
		
		
		
		
}





