package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * Portal Source Status enumeration.
 * */
public abstract class PortalSourceStatus {

	@IntDef(flag=true, value={Deleteable, Created, Initialized, Active})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

			/** Deleteable. The portal object has been disabled.&nbsp;
			 * "Garbage Collection" should dispose and delete the object on the next occasion.
			 * "Garbage Collection" should dispose and delete the object on the next occasion.
			 * */
	public static final int Deleteable          	=	0;
			/** The portal has just been created. */
	public static final int Created             	=	1;
			/** Initialized. The portal is initialized, that is the resources (threads, plugins, the pipeline) has been established or are ready to use */
	public static final int Initialized         	=	2;
			/** Active. The portal is initialized and actively streaming. */
	public static final int Active              	=	3;
		
}





