package environs;

/* DO NOT EDIT THIS FILE - it is machine generated by j2c.jar */

/**
 * ------------------------------------------------------------------
 * Copyright (c) Chi-Tai Dang
 *
 * @author	Chi-Tai Dang
 * @version	1.0
 *
 * This file is part of the Environs framework developed at the
 * Lab for Human Centered Multimedia of the University of Augsburg.
 * http://hcm-lab.de/environs
 *
 * Environ is free software; you can redistribute it and/or modify
 * it under the terms of the Eclipse Public License v1.0.
 * A copy of the license may be obtained at:
 * http://www.eclipse.org/org/documents/epl-v10.html
 * --------------------------------------------------------------------
 */
import android.support.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/** 
 * Portal types enumeration. Represents the same values as for PORTAL_TYPE_* 
 * */
public abstract class PortalType {

	@IntDef(flag=true, value={Any, Screen, BackCam, FrontCam})

	@Retention(RetentionPolicy.SOURCE)
	public @interface Value {}

			/** Any type. The requested portal can be of any type. Which one depends on the application logic.
			 * */
	public static final int Any                 	=	Types.PORTAL_TYPE_ANY;
			/** The devices screen. */
	public static final int Screen              	=	Types.PORTAL_TYPE_SCREEN;
			/** The back facing camera. */
	public static final int BackCam             	=	Types.PORTAL_TYPE_BACK_CAM;
			/** The front facing camera. */
	public static final int FrontCam            	=	Types.PORTAL_TYPE_FRONT_CAM;
}





