#!/bin/bash

cd Simple.Console.CPP
make clean
make 
cd -

cd Echo.Bot.CPP
make clean
make 
cd -

if [[ -e ./Plugins/ExtWifiObserver ]]; then
	cd Plugins/ExtWifiObserver
	make clean
	make 
	cd -
fi

make clean
make

